### ISSUE TITLE
QGIS 3.22.4 closes when trying to activate "Lat Lon Tools"

### ISSUE THREAD

**Issue by maximilianharr** [NationalSecurityAgency/qgis-latlontools-plugin#88]
Hi everyone,
I'm new to OSS but have been writing python code and using github for some years. I'd like to help resolve an issue with this plugin we found lately and would be very grateful for some guidance/mentor.

After installation of "Lat Lon Tools" plugin in QGIS 3.22.4-Białowieża the window closes when trying to activate the plugin.
To reproduce follow these steps: Plugins > Manage and Install Plugins ... > Installed > Lat Lon Tools (activate checkbox).

Eager to get some feedback on how to fix and test this issue.

Regards, Max

**Comment by hamiltoncj** [comment]
I am not sure what the problem is you are encountering. Lat Lon Tools seems to be functioning properly on my end. I tried it with QGIS 3.22.2 and it was working fine. Lat Lon Tools has been downloaded more than 857,000 times and no one has indicated there was a problem so I suspect that what you are experiencing is actually something else. Perhaps you could give me some more details about what is happening.

**Comment by hamiltoncj** [comment]
I made a change today. Try the new version (3.6.15) and see if it solves the problem. If not please give me more information.

**Comment by hamiltoncj** [comment]
I am just checking back. I fixed one bug that may be the issue you are talking about. Please give the latest version a try.

**Comment by maximilianharr** [comment]
Thanks @hamiltoncj 3.6.15 seems to be still failing with QGIS 3.22.4 for me. I'm currently on vacation and give it a more thoroughly check next week

**Comment by hamiltoncj** [comment]
Can not replicate so closing due to lack for further input.

**Comment by zerolover** [comment]
Maybe the same issue of https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/issues/72
The reason is that two different version of pyproj are installed which can be verified by:
`dpkg -l | grep python3-pyproj`
`pip3 list | grep pyproj`

So, there are two solutions:
1. uninstall pyproj(or install it in conda, virtualenv ...)
2. comments `import pyproj` in https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/blob/master/ecef.py
for ubuntu, the path is ~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/latlontools/ecef.py

@hamiltoncj @maximilianharr
